### ISSUE TITLE
How to run this flake?

### ISSUE THREAD

**Issue by iluuu1994** [eraserhd/nix-zmk#1]
Hi! Sorry, I'm a complete nix noob. I was looking for a way to compile my zmk layout locally without installing all the dependencies and stumbled across this repo. Would it be possible to add a small readme to demonstrate how this can be used? Thank you so much!

I tried running `nix develop` but get the following error:

> error: flake 'path:/home/ilutov/Downloads/nix-zmk-main' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'

I tried various arguments but wasn't successful.

**Comment by eraserhd** [comment]
Hi.   Ths repo is barely put together, and I'm not sure what state it is in.  It looks like `nix shell` is intended.  I think I got it sort of working before I switched back to QMK.

**Comment by iluuu1994** [comment]
I see. I used a docker-container which works well enough. Thanks!
